### ISSUE TITLE
Work with GHC 8.4

### ISSUE THREAD

**Issue by ndmitchell** [tibbe/unordered-containers#174]
I get the error:

```
[8 of 8] Compiling Data.HashSet     ( Data/HashSet.hs, dist/build/Data/HashSet.o )
Data/HashSet.hs:80:39: error:
    Module ‘Data.Semigroup’ does not export ‘Monoid(..)’
   |
80 | import Data.Semigroup (Semigroup(..), Monoid(..))
   |                                       ^^^^^^^^^^
```

Now that `primitive` is working this is the next thing stopping me from testing shake (and experience is that shake trips at least one new segfault in every GHC...)

**Comment by treeowl** [comment]
I need to make a containers release real quick to make the 8.4 deadline, so
unfortunately it may take a couple days for me to get to an
unordered-containers release. But worry not: it will not drag on.

**Comment by treeowl** [comment]
I've tagged a release, but @tibbe seems to be the only one with Hackage permissions right now. I sent him an email.

**Comment by treeowl** [comment]
Uploaded to Hackage!
