### PR TITLE
Create ReadTheDocs project for unordered-containers.

### LINKED ISSUE #173: Add external, beginner friendly docs
Hey, I recently wrote up some external docs for the `containers` package which [appears to be well received](https://www.reddit.com/r/haskell/comments/7nvjr2/rfc_a_beginner_friendly_introduction_to_haskell/). I was wondering if you would accept a pull request for similar docs for this package. They would be the same format as the `container` docs and would live at haskell-unordered-containers.readthedocs.io.

Let me know what you think!

### PR DESCRIPTION
**Pull request by m-renaud**
These docs walk a newcomer through the unordered-containers package.

Content includes:
- Overview of what's available in the package
- Related packages
- Links to more resources
- How to import and add a dependency on the package
- Walk through common functions from HashSet and HashMap

Rendered docs can be found at https://m-renaud-haskell-unordered-containers.readthedocs.io/en/m-renaud-docs-user-guide/

Once approved these will be published at https://haskell-unordered-containers.readthedocs.io.

This resolves #173.  

/cc @treeowl for review

### CODE REVIEW

**Comment by m-renaud** [comment]
Friendly ping @treeowl :)

File: docs/conf.py [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+templates_path = ['_templates']
+
+source_suffix = '.rst'
+
+master_doc = 'index'
+
+# General information about the project.
+project = u'unordered-containers'
+copyright = u'2020, Matt Renaud'
+author = u'Matt Renaud'
```
Comment (emilypi) [inline docs/conf.py:33]: Should this include the data of the original licenses, or is this just for the RTD?

File: docs/hash-map.rst [hunk 2]
```diff
@@ -0,0 +1,578 @@
...
+    > fromList [(1,"uno"),(2,"two"),(3,"three")]
+
+    HashMap.difference (HashMap.fromList[(1,"one"), (2,"two")]) (HashMap.fromList [(1,"uno")])
+    > fromList [(2,"two")]
+
+
+Serialization
+-------------
+
+TODO(m-renaud): Serialization docs.
```
Comment (emilypi) [inline docs/hash-map.rst:563]: This is rendered in the [docs](https://m-renaud-haskell-unordered-containers.readthedocs.io/en/m-renaud-docs-user-guide/hash-set.html#serialization). Wrong format, or still a valid TODO?

File: docs/hash-map.rst [hunk 3]
```diff
@@ -0,0 +1,578 @@
...
+    > Just "one"
+
+    HashMap.lookupDefault "?" k HashMap.empty
+    > "?"
+
+    HashMap.lookupDefault "?" 1 (Map.fromList [(1,"one"), (2,"two"), (3,"three")])
+    > "one"
+
+.. WARNING::
+   **DO NOT** Use ``HashMap.!``. It is partial and throws a runtime error if
```
Comment (emilypi) [inline docs/hash-map.rst:262]: This is a bit prescriptive, like saying never use `head`. Can we just say ```**DO NOT** use `HashMap.! if you are expecting a total function or cannot tolerate a runtime errors``` ?

File: docs/hash-set.rst [hunk 4]
```diff
@@ -0,0 +1,386 @@
...
+    > fromList [0,2,4,6]
+
+    HashSet.difference (HashSet.fromList [0, 2, 4, 6]) (HashSet.singleton 0)
+    > fromList [2,4,6]
+
+
+Serialization
+-------------
+
+TODO(m-renaud): Write serialization section.
```
Comment (emilypi) [inline docs/hash-set.rst:371]: Same here

File: docs/conf.py (hunk 1 above)
Comment (m-renaud) [reply docs/conf.py:33]: This is just for the docs, but I'm happy to change the copyright and author fields to "unordered-container maintainers". Wdyt?

Comment (emilypi) [reply docs/conf.py:33]: Works for me - that'd be great 😄

File: docs/hash-map.rst (hunk 2 above)
Comment (m-renaud) [reply docs/hash-map.rst:563]: Valid Todo, I was going to ask if there is a recommended way to serialize the unordered-container data types. Many serialization libraries support containers (https://haskell-containers.readthedocs.io/en/latest/set.html#serialization for example) but I wasn't sure what's best to put here. Maybe just omit this section for now (here and where your other comment is)? Open to suggestions :)

Comment (emilypi) [reply docs/hash-map.rst:563]: I think that's a question for the expert - @treeowl ^

File: docs/conf.py (hunk 1 above)
Comment (m-renaud) [reply docs/conf.py]: Update.

File: docs/hash-map.rst (hunk 3 above)
Comment (m-renaud) [reply docs/hash-map.rst]: Reworded to be a bit of a mix of both. PTAL!

File: docs/hash-set.rst (hunk 4 above)
Comment (m-renaud) [reply docs/hash-set.rst]: Removed TODO's, can add serialization section in a follow-up PR if desired.

File: docs/hash-map.rst (hunk 2 above)
Comment (m-renaud) [reply docs/hash-map.rst]: Removed Serialization sections for the time being, can add them in a follow-up PR if desired.

**Comment by emilypi** [comment]
@m-renaud why the change? `HashMap.!?` doesn't seem to exist for `HashMap`, and would be a total function if it did, meaning the docs are out of date. `HashMap.!` is the partial function, which could throw.

**Comment by m-renaud** [comment]
Oops, that was actually a mistake, I was looking at the wrong section of the docs. Undone.

**Comment by m-renaud** [comment]
Oh wait, you're right, `!?` doesn't exist either :/

**Comment by m-renaud** [comment]
@emilypi see #175.

**Comment by emilypi** [comment]
It'll exist soon! Great. We can add more docs when it's merged. As is, with your changes here, we should be good to merge this.

**Comment by emilypi** [comment]
@sjakobi your eyes would be appreciated.

**Comment by sjakobi** [comment]
Thanks for doing this, @m-renaud! :) I think this kind of introductory documentation is very important.

Nevertheless, I wish that this was integrated in the haddocks:

* Better discoverability
* 2 markup languages (Markdown and Haddock) instead of 3 (RST)
* Higher likelihood IMO to see further improvements by other contributors
* Less indecision where future documentation improvements should be added
* No need to apply documentation updates in two places

Would you consider converting this into one or several tutorial modules in the style of [`Generic.Random.Tutorial`](http://hackage.haskell.org/package/generic-random-1.3.0.1/docs/Generic-Random-Tutorial.html) or [`Pipes.Tutorial`](http://hackage.haskell.org/package/pipes-4.3.13/docs/Pipes-Tutorial.html)? I think this could at least partially be automated with [`pandoc`](https://pandoc.org/).

**Comment by m-renaud** [comment]
Thanks for the feedback @sjakobi! I briefly considered putting the tutorial in the haddocks but opted for RST + ReadTheDocs for a few reasons:

* Formatting: (imho) significantly nicer formatting, navigation, and search within the documents than you get with haddock
  * Specifically, the custom formatting for TIP, IMPORTANT, WARNING, etc. makes a pretty big difference in readability.
  * You can kinda tell that Haddock was designed with API docs in mind, and less so free form content.
  * Also, different renderings based on if you're browsing on hackage or stackage (I think stackage's rendering is much better)
* Independent doc releases
  * No need to release a new version of the package to fix/modify/improve docs
* RST is (ihmo) an easier format to write/read than Haddocks
  * TBH I find the haddock markup a little obtuse for writing mostly free-form content, looking at [`Tutorial.hs`](https://github.com/Gabriel439/Haskell-Pipes-Library/blob/master/src/Pipes/Tutorial.hs) from pipes there's a weird mix of `{-`, `>`, four space indents, `>>>`, `@` for formatting code, and the majority of the content needs to be indented since its mostly text. RST is incredibly similar to markdown, but with a slightly different syntax for links and x-refs. 
* Doesn't introduce an extraneous "not actually part of the package module", just for the purpose of creating a page in the docs.
  *  This is another set of modules that needs to be parsed/built whenever you build the package. Obviously not a deal breaker, but at least for `containers` and `unordered-containers` which are a dependency of a large number of projects, introducing 4-8 additional modules to build (even if they're simple) every time their used seems non-ideal.
* Branding: Haskell docs have a bad reputation of not being beginner friendly, and API docs are not always the ideal place to start if you're new (to Haskell, or a given package).
  * I was imagining an "intro docs" branding which is separate from API docs and has a consistent form and theme which brings some amount of familiarity, in this case the ReadTheDocs format and the green Haskell logo (green ~= fresh/new or something :upside_down_face: )

To speak to the specific points you've raised:

> Better discoverability

Having a sentence at/near the top of the entrypoint into the docs referring to the (external) docs doesn't seem much different than having a sentence which refers to the `Tutorial` module. (see the following in the containers package).

image

Also, SEO should take care of indexing it properly as well, for example here's a search for `haskell containers tutorial`:

image

> 2 markup languages (Markdown and Haddock) instead of 3 (RST)

That's a fair point, I don't think RST is _that_ much different than Markdown, but its still slightly different.

> Higher likelihood IMO to see further improvements by other contributors

I actually think its the opposite, with ReadTheDocs each page has a direct link to where you can edit the documentation right from the rendered docs, which I think actually lowers the barrier for making edits. Additionally, as I mentioned above, changing haddocks requires a new release of the package for the changes to take affect which may dissuade external contributors.

image


> Less indecision where future documentation improvements should be added

Eh, I can buy that, but also a specific directory named `docs/` in the top level of the package is pretty discoverable. 

> No need to apply documentation updates in two places

If you're adding/changing a function in a module, you still need to know to update the "intro docs", regardless of if that lives at `Tutorial.HashMap` or `docs/hash-map.rst`. /shrug

I'd love to hear your thoughts on my points above! In any case, if you feel strongly that this should live in a `Tutorial` module I can take a stab at doing so, but I think it will result in a sub-optimal final product as compared to ReadTheDocs.

**Comment by emilypi** [comment]
Sorry for potentially expanding the scope of this already sizable PR, but @m-renaud, #175 is now in, if you want to add the docs for `(!?)` while we come to a decision.

**Comment by m-renaud** [comment]
No worries, it's always good to get more opinions :) And yeah I can do that, I'm presuming there a plan to cut a new release of the package soon so that the documented `!?` actually exists, yeah?

**Comment by emilypi** [comment]
I should hope so 😄. I'm going to go through the merges since last release and put together a criteria for the next release. It should include the space leak fixes, the new combinators, and also most of these new doc changes.

**Comment by sjakobi** [comment]
You make good points @m-renaud! I'm very happy that you care and have thought about this stuff so deeply! :+1: 

I'll respond to some of your arguments:



> * Also, different renderings based on if you're browsing on hackage or stackage (I think stackage's rendering is much better)

Haddock's default style was changed with GHC-8.10 (or 8.8 already?), bringing it closer to Stackage's style.

> Independent doc releases
> * No need to release a new version of the package to fix/modify/improve docs

I wouldn't mind making releases for documentation improvements, and will do so, if @treeowl gives me upload permissions.

Having a separate process for documentation changes, with separate permissions also makes things more complicated.


> * RST is (ihmo) an easier format to write/read than Haddocks

Haddock markup is admittedly tricky. At this point I'm sufficiently experienced with it that it's probably easier for me than writing RST though. In my experience RST has its pitfalls too though, and the subtle differences from Markdown don't exactly help.

Since this documentation is targeted at beginners, who are unlikely to know either Haddock or RST, I believe the ideal markup language to invite contributions would actually be Markdown!



> Doesn't introduce an extraneous "not actually part of the package module", just for the purpose of creating a page in the docs.
> * This is another set of modules that needs to be parsed/built whenever you build the package. Obviously not a deal breaker, but at least for `containers` and `unordered-containers` which are a dependency of a large number of projects, introducing 4-8 additional modules to build (even if they're simple) every time their used seems non-ideal.

You're not wrong, but I also don't believe that the effect on compile times is large enough that this matters.

In fact, having these docs included in the haddocks, means that people can simply build them locally, e.g. with the classic `stack haddock --open unordered-containers`.



> Branding: Haskell docs have a bad reputation of not being beginner friendly, and API docs are not always the ideal place to start if you're new (to Haskell, or a given package).
> * I was imagining an "intro docs" branding which is separate from API docs and has a consistent form and theme which brings some amount of familiarity, in this case the ReadTheDocs format and the green Haskell logo (green ~= fresh/new or something upside_down_face )

This is an intriguing idea! IMHO the better way to improve the reputation of Haskell library docs would be to improve the existing ones though. Even if you can pull off writing and publishing "intro docs" for a large swath of libraries, people will still encounter the (bad) old ones and might be put off.



> Also, SEO should take care of indexing it properly as well, for example here's a search for `haskell containers tutorial`:

If we'd come to a point where searching for "unordered-containers docs" would give results for both the ReadTheDocs site and Hackage, I think that could cause confusion too…



> > Higher likelihood IMO to see further improvements by other contributors
> 
> I actually think its the opposite, with ReadTheDocs each page has a direct link to where you can edit the documentation right from the rendered docs, which I think actually lowers the barrier for making edits.

Not a bad point. I'm under the impression though that your intro docs for `containers` haven't received any contributions from other people, while the haddocks have received quite a few… Have other intro docs of yours seen more contributions?



> > Less indecision where future documentation improvements should be added
> 
> Eh, I can buy that, but also a specific directory named `docs/` in the top level of the package is pretty discoverable.

I didn't mean an issue with discoverability here, but rather that when there are two separate "documentation trees", that might lead to some decision paralysis on where best to document certain things.



> In any case, if you feel strongly that this should live in a `Tutorial` module I can take a stab at doing so, but I think it will result in a sub-optimal final product as compared to ReadTheDocs.

I feel bad to ask you for more after all the work you've already put into this! Nevertheless I think it's worth giving this a spin. Maybe just try it with a single page. If we still end up preferring the ReadTheDocs version, I'm definitely in favour of publishing it!

**Comment by m-renaud** [comment]
> Haddock's default style was changed with GHC-8.10 (or 8.8 already?), bringing it closer to Stackage's style.

Oh great!

> Having a separate process for documentation changes, with separate permissions also makes things more complicated.

The docs auto-rebuild whenever they're changed, so pretty minimal overhead (can also be done manually with a single button push).

> If we'd come to a point where searching for "unordered-containers docs" would give results for both the ReadTheDocs site and Hackage, I think that could cause confusion too…

Eh, I don't think its uncommon for intro/beginner tutorials being hosted separately from API docs, as long as there's cross links I don't think it would be much of an issue.

> I'm under the impression though that your intro docs for containers haven't received any contributions from other people

It actually has at least 5 unique contributions (https://github.com/haskell/containers/commit/8b0b60081938ff849bbec97aeb4678d99a6a7232, https://github.com/haskell/containers/commit/58ca823d6042b8552b4d2c05474282ce65171869, https://github.com/haskell/containers/commit/0f614495cc98696b3841e85ab6ec2e79cb961aa4, https://github.com/haskell/containers/commit/3a343a3f6353bc60c8766dfd564646210f2b06bd, https://github.com/haskell/containers/commit/17494c9ecd5c5cf54d9cd11c7698f57b3945a0dd)! 

The files were all moved into a different directory which apparently didn't maintain "history" but they still show up in "blame".


> Nevertheless I think it's worth giving this a spin.

I migrated some of the content to a `Tutorial` and `Tutorial.HashSet`. Just my opinion, but the formatting and navigation are worse than on RTD. Specifically:

* navigation to other parts of the tutorial require you to click on the "Contents" menu at the top then navigate to another module, you can't just quickly see and jump to other parts of the tutorial
* Lack of IMPORTANT, TIP, WARNING formatting is unfortunate
* Code formatting is not syntax highlighted
* No search functionality
* Only top-level headings, to have sub-heading you have to use bold/italic and manually attach hyperlinks, and I can't find a way to have them in the TOC

I'm also a bit of a Haddock noob, so its possible that there are ways to make the above better.

**Comment by m-renaud** [comment]
**ReadTheDocs:**

image

**Haddocks**

image

**Comment by m-renaud** [comment]
Open questions:

* How can I get syntax highlighting in code blocks (`@`...`@`) that also maintains the `HashSet.` prefix? If I wrap a call to `HashSet.foo` with quotes it strips the `HashSet.` prefix in the rendered docs and just links to the function.

* How can I get subheaders to show up in the TOC?

* Any tips for improving navigation between tutorial modules?

**Comment by sjakobi** [comment]
Many thanks for giving this a spin, @m-renaud!

I'm having some trouble building your branch though:

```
$ cabal build unordered-containers
Resolving dependencies...
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - unordered-containers-0.2.10.0 (lib) (first run)
<snip>
Data/HashMap/Strict.hs:40:7-21: error:
    Not in scope: ‘findWithDefault’
   |
40 |     , findWithDefault
   |       ^^^^^^^^^^^^^^^
```

I'm quite mystified where that error comes from. CI is green too…

How did you build the haddocks locally?

**Comment by sjakobi** [comment]
I can reproduce the build failure in da5ac39fb4d82af8af43a2e981fa4c6f0c8d20db, the parent commit of your branch. Rebasing on top of `master` fixes it.

**Comment by m-renaud** [comment]
Yup, looks looks an old base CL, rebased and re-pushed commits.

**Comment by m-renaud** [comment]
Thanks for the suggestions @sjakobi, I am indeed not experienced with Haddock markup :upside_down_face:. I think I'll have some time tonight to fix the markup in the existing docs and add a bit more content.

**Comment by m-renaud** [comment]
> Support for [anchors](https://haskell-haddock.readthedocs.io/en/latest/markup.html#anchors)

Oh look! Haddock [uses RST](https://github.com/haskell/haddock/blob/ghc-head/doc/markup.rst) for its user-facing docs :stuck_out_tongue_winking_eye:

**Comment by sjakobi** [comment]
BTW another IMHO pretty good-looking tutorial module is http://hackage.haskell.org/package/turtle-1.5.19/docs/Turtle-Tutorial.html. Of course, it's also by Gabriel Gonzalez!

File: Tutorial.hs [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    -- $installing
+
+    -- * HashSet and HashMap tutorial
+    -- $tutorials
+
+                ) where
+
+{- $provideddatastructures
+* 'Data.HashSet' - unordered, non-duplicated elements
+* 'Data.HashMap' - unordered map from keys to values (aka. dictionaries)
```
[the remark this answers is not in the document]
Comment (m-renaud) [reply Tutorial.hs]: Fixed.

File: Tutorial/HashSet.hs [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+data 'HashSet' element = ...
+@
+
+
+All of these implementations are *immutable* which means that any update
+functions do not modify the set that you passed in, they creates a new set. In
+order to keep the changes you need to assign it to a new variable. For example:
+
+@
+let s1 = 'HashSet.fromList' ["a", "b"]
```
[the remark this answers is not in the document]
Comment (m-renaud) [reply Tutorial/HashSet.hs]: Hmm, that's a little ugly, but it works.

File: Tutorial/HashSet.hs [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+import qualified Data.HashSet as HashSet
+
+{- $shortexample
+
+The following GHCi session shows some of the basic set functionality:
+
+@
+import qualified 'Data.HashSet' as HashSet
+
+let dataStructures = 'HashSet.fromList' ["HashSet", "HashMap", "Graph"]
```
[the remark this answers is not in the document]
Comment (m-renaud) [reply Tutorial/HashSet.hs]: Done.

**Comment by m-renaud** [comment]
Added some more content for comparison. Outstanding issues:

- Multiple levels of sub-headings are pretty annoying since you need to split every piece into its own `{- .. -}` block, and the the title of the section is separate from the content
- Lack of syntax highlighting in code blocks (strings, numbers, etc. aren't highlighted)
- Special formatting for TIP, WARNING, etc. non existant
- Navigation between different tutorial modules isn't possible in one click (need to know to click "Contents" and then find the "Tutorial" module in the list)

Do you think it would be helpful to solicit some more opinions?

**Comment by sjakobi** [comment]
I'm getting a build failure again:

```
$ cabal haddock --enable-documentation --haddock-for-hackage unordered-containers
Resolving dependencies...
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - unordered-containers-0.2.10.0 (lib) (first run)
Configuring library for unordered-containers-0.2.10.0..
Preprocessing library for unordered-containers-0.2.10.0..
cabal: can't find source for Tutorial/HashMap in .,
/home/simon/src/unordered-containers/dist-newstyle/build/x86_64-linux/ghc-8.10.1/unordered-containers-0.2.10.0/build/autogen,
/home/simon/src/unordered-containers/dist-newstyle/build/x86_64-linux/ghc-8.10.1/unordered-containers-0.2.10.0/build/global-autogen

cabal: Failed to build documentation for unordered-containers-0.2.10.0.
```

**Comment by sjakobi** [comment]
FWIW, I've started to make a list of tutorial modules here: https://github.com/sjakobi/awesome-haskell-tutorial-modules :smile:

**Comment by m-renaud** [comment]
Oops, forgot to git add the new file.

**Comment by m-renaud** [comment]
@sjakobi to throw another option out there:

Have the examples and walkthroughs in the module documentation as is done in Rust (see https://doc.rust-lang.org/1.5.0/std/collections/struct.HashMap.html for example), instead of a separate Tutorial module. Then we could improve the inline haddocks for the the individual functions to contain examples and better explanations, and then re-arrange the sections a bit. wdyt?

Aside: It may not be a great fit for this type of content, but the modules should probably have an example usage in them anyways.
